version: "3"
services:
  reverseproxy:
      image: manojbokku/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: manojbokku/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: $Env:POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $Env:POSTGRESS_PASSWORD 
      POSTGRESS_DB: $Env:POSTGRESS_DB 
      POSTGRESS_HOST: $Env:POSTGRESS_HOST 
      AWS_REGION: $Env:AWS_REGION 
      AWS_PROFILE: $Env:AWS_PROFILE 
      AWS_BUCKET: $Env:AWS_BUCKET
      JWT_SECRET: $Env:JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: manojbokku/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $Env:POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $Env:POSTGRESS_PASSWORD 
      POSTGRESS_DB: $Env:POSTGRESS_DB 
      POSTGRESS_HOST: $Env:POSTGRESS_HOST 
      AWS_REGION: $Env:AWS_REGION 
      AWS_PROFILE: $Env:AWS_PROFILE 
      AWS_BUCKET: $Env:AWS_BUCKET
      JWT_SECRET: $Env:JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: manojbokku/udacity-frontend:local
    ports:
      - "8100:80"
